#!/bin/bash

# Checking if the required arguments are present - the openrc ${1}, the tag ${2} and the ssh_key ${3}
# The program will not run if these arguments are not present.
: ${1:?" Please specify the openrc, tag, and ssh_key"}
: ${2:?" Please specify the openrc, tag, and ssh_key"}
: ${3:?" Please specify the openrc, tag, and ssh_key"}


cd_time=$(date)
openrc_sr=${1}     # Fetching the openrc access file
tag_sr=${2}        # Fetching the tag for easy identification of items
ssh_key_sr=${3}    # Fetching the ssh_key for secure remote access
no_of_servers=$(grep -E '[0-9]' servers.conf) # Fetching the number of nodes from servers.conf

# Begin deployment by sourcing the given openrc file
echo "${cd_time} Starting deployment of $tag_sr using ${openrc_sr} for credentials."
source ${openrc_sr}


# Define variables
natverk_namn="${2}_network"
sr_subnet="${2}_subnet"
sr_keypair="${2}_key"
sr_router="${2}_router"
sr_security_group="${2}_security_group"
sr_haproxy_server="${2}_proxy"
sr_bastion_server="${2}_bastion"
sr_server="${2}_dev"
vip_port="${2}_vip" #virtual ip port
sshconfig="config"
knownhosts="known_hosts"
hostsfile="hosts"

# Check for current keypairs

echo "$(date) Checking if we have ${sr_keypair} available."
current_keypairs=$(openstack keypair list -f value --column Name)
if echo "${current_keypairs}" | grep -qFx ${sr_keypair}
then
    echo "$(date) ${sr_keypair} already exists"
else    
    new_keypair=$(openstack keypair create --public-key ${ssh_key_sr} "$sr_keypair" )
    echo "$(date)  Adding ${sr_keypair} associated with ${ssh_key_sr}."
fi

# Checking current networks corresponding to the tag
current_networks=$(openstack network list --tag "${tag_sr}" --column Name -f value)
if echo "${current_networks}" | grep -qFx ${natverk_namn} 
then
    echo "$(date) ${natverk_namn} already exists"
else
    echo "$(date) Did not detect ${natverk_namn} in the OpenStack project, adding it."
    new_network=$(openstack network create --tag "${tag_sr}" "${natverk_namn}" -f json)
    echo "$(date) Added ${natverk_namn}."
fi

